package presidenttipeli.gui;

import presidenttipeli.logiikka.OstoJaMyynti;

public class OstoJaMyyntiGUI extends javax.swing.JFrame implements Runnable {

    public OstoJaMyyntiGUI(OstoJaMyynti ostoJaMyynti) {
        this.ostoJaMyynti = ostoJaMyynti;
        run();
    }

    @Override
    public void run() {
        initComponents();
        kustomoiGUI();
        asetaNappuloilleActionListener();
        this.setVisible(true);
    }

    private void kustomoiGUI() {
        if (ostoJaMyynti.isRuutu20()) {
            eiVoiOstaaLiiketta();
        }
        if (!ostoJaMyynti.isSaaMyyda()) {
            eiSaaMyyda();
        }

        if (ostoJaMyynti.getPelaajanLiikkeet().length == 0) {
            eiVoiMyydaLiikkeita();
        }

        if (ostoJaMyynti.getPelaajanMokit().length == 0) {
            eiVoiMyydaMokkeja();
        }
        
        if (!ostoJaMyynti.riittaakoRahatMokkiin()) {
            eiVoiOstaaMokkia();
        }
        
        if (!ostoJaMyynti.riittaakoRahatLiikkeeseen()) {
            eiVoiOstaaLiiketta();
        }
        
        if (ostoJaMyynti.isRuutu16Tarjous()) {
            myyMokki.setText("Myy 2x hinnalla");
            myyLiike.setText("Myy 2x hinnalla");
        }
        
        if (ostoJaMyynti.getPaallimmainenMokki() == null) {
            eiMokkejaJaljella();
            eiVoiOstaaMokkia();
        } else {
            asetaMokinTiedot();
        }
        
        if (ostoJaMyynti.getPaallimmainenLiike() == null) {
            eiLiikkeitaJaljella();
            eiVoiOstaaLiiketta();
        } else {
            asetaLiikkeenTiedot();
        }
    }
    
    private void asetaNappuloilleActionListener() {
        actionlistener = new OstoJaMyyntiActionListener(myyLiike, myyMokki, okButton,
        ostaLiike, ostaMokki, pelaajanLiikkeet, pelaajanMokit, this, ostoJaMyynti);
        myyLiike.addActionListener(actionlistener);
        myyMokki.addActionListener(actionlistener);
        okButton.addActionListener(actionlistener);
        ostaLiike.addActionListener(actionlistener);
        ostaMokki.addActionListener(actionlistener);
    }

    private void eiSaaMyyda() {
        eiVoiMyydaLiikkeita();
        eiVoiMyydaMokkeja();
    }

    private void eiVoiMyydaMokkeja() {
        myyMokkiJLabel.setEnabled(false);
        pelaajanMokit.setEnabled(false);
        myyMokki.setEnabled(false);
    }

    private void eiVoiMyydaLiikkeita() {
        myyLiikeJLabel.setEnabled(false);
        pelaajanLiikkeet.setEnabled(false);
        myyLiike.setEnabled(false);
    }

    private void eiVoiOstaaLiiketta() {
        liikeJLabel.setEnabled(false);
        liikeNimiJLabel.setEnabled(false);
        liikeArvoJLabel.setEnabled(false);
        liikeTuottoJLabel.setEnabled(false);
        ostaLiike.setEnabled(false);
        liikkeenArvo.setEnabled(false);
        liikkeenNimi.setEnabled(false);
        liikkeenTuotto.setEnabled(false);
    }
    
    private void eiVoiOstaaMokkia() {
        mokkiJLabel.setEnabled(false);
        mokkiNimiJLabel.setEnabled(false);
        mokkiArvoJLabel.setEnabled(false);
        ostaMokki.setEnabled(false);
        mokinNimi.setEnabled(false);
        mokinArvo.setEnabled(false);
    }
    
    private void eiMokkejaJaljella() {
        mokinNimi.setText("Ei mökkejä jäljellä");
        mokinArvo.setText("Ei mökkejä jäljellä");
    }
    
    private void eiLiikkeitaJaljella() {
        liikkeenNimi.setText("Ei liikkeita jäljellä");
        liikkeenArvo.setText("Ei liikkeita jäljellä");
        liikkeenTuotto.setText("Ei liikkeita jäljellä");
    }
    
    private void asetaMokinTiedot() {
        mokinNimi.setText(ostoJaMyynti.getPaallimmainenMokki().getNimi());
        mokinArvo.setText(ostoJaMyynti.getPaallimmainenLiike().getArvo() + " mk");
    }
    
    private void asetaLiikkeenTiedot() {
        liikkeenNimi.setText(ostoJaMyynti.getPaallimmainenLiike().getTyyppi() + " "
        + ostoJaMyynti.getPaallimmainenLiike().getNimi());
        liikkeenArvo.setText(ostoJaMyynti.getPaallimmainenLiike().getArvo() + " mk");
        liikkeenTuotto.setText(ostoJaMyynti.getPaallimmainenLiike().getArvo() + " mk/kk");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pelaajanNimi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pelaajanRahat = new javax.swing.JLabel();
        mokkiJLabel = new javax.swing.JLabel();
        mokkiNimiJLabel = new javax.swing.JLabel();
        mokkiArvoJLabel = new javax.swing.JLabel();
        mokinArvo = new javax.swing.JLabel();
        liikeJLabel = new javax.swing.JLabel();
        liikeNimiJLabel = new javax.swing.JLabel();
        liikeArvoJLabel = new javax.swing.JLabel();
        liikkeenArvo = new javax.swing.JLabel();
        liikeTuottoJLabel = new javax.swing.JLabel();
        liikkeenTuotto = new javax.swing.JLabel();
        ostaMokki = new javax.swing.JButton();
        ostaLiike = new javax.swing.JButton();
        myyMokkiJLabel = new javax.swing.JLabel();
        pelaajanMokit = new javax.swing.JComboBox();
        myyLiikeJLabel = new javax.swing.JLabel();
        pelaajanLiikkeet = new javax.swing.JComboBox();
        myyMokki = new javax.swing.JButton();
        myyLiike = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        liikkeenNimi = new javax.swing.JTextField();
        mokinNimi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Pelaaja:");

        pelaajanNimi.setText(ostoJaMyynti.getPelaaja().getNimi());

        jLabel2.setText("Pelaajan rahat:");

        pelaajanRahat.setText(ostoJaMyynti.getPelaaja().getRahat() + " mk");

        mokkiJLabel.setText("Mökki:");

        mokkiNimiJLabel.setText("Nimi:");

        mokkiArvoJLabel.setText("Arvo:");

        mokinArvo.setText("Arvo");

        liikeJLabel.setText("Liike:");

        liikeNimiJLabel.setText("Nimi:");

        liikeArvoJLabel.setText("Arvo:");

        liikkeenArvo.setText("Arvo");

        liikeTuottoJLabel.setText("Tuotto:");

        liikkeenTuotto.setText("Tuotto");

        ostaMokki.setText("Osta");

        ostaLiike.setText("Osta");

        myyMokkiJLabel.setText("Pelaajan mökit:");

        pelaajanMokit.setModel(new javax.swing.DefaultComboBoxModel(ostoJaMyynti.getPelaajanMokit()));

        myyLiikeJLabel.setText("Pelaajan liikkeet:");

        pelaajanLiikkeet.setModel(new javax.swing.DefaultComboBoxModel(ostoJaMyynti.getPelaajanLiikkeet()));

        myyMokki.setText("Myy");

        myyLiike.setText("Myy");

        okButton.setText("OK");

        liikkeenNimi.setEditable(false);
        liikkeenNimi.setText("Nimi");

        mokinNimi.setEditable(false);
        mokinNimi.setText("Nimi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pelaajanNimi))
                            .addComponent(mokkiJLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mokkiNimiJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mokinNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mokkiArvoJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mokinArvo))
                            .addComponent(ostaMokki)
                            .addComponent(myyMokkiJLabel)
                            .addComponent(pelaajanMokit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myyMokki))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myyLiike)
                            .addComponent(pelaajanLiikkeet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myyLiikeJLabel)
                            .addComponent(ostaLiike)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(liikeTuottoJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(liikkeenTuotto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(liikeArvoJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(liikkeenArvo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(liikeNimiJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(liikkeenNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(liikeJLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pelaajanRahat))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(okButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pelaajanNimi)
                    .addComponent(jLabel2)
                    .addComponent(pelaajanRahat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mokkiJLabel)
                    .addComponent(liikeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mokkiNimiJLabel)
                    .addComponent(liikeNimiJLabel)
                    .addComponent(liikkeenNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mokinNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mokkiArvoJLabel)
                    .addComponent(mokinArvo)
                    .addComponent(liikeArvoJLabel)
                    .addComponent(liikkeenArvo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liikeTuottoJLabel)
                    .addComponent(liikkeenTuotto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ostaMokki)
                    .addComponent(ostaLiike))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myyMokkiJLabel)
                    .addComponent(myyLiikeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pelaajanMokit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelaajanLiikkeet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myyLiike)
                    .addComponent(myyMokki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel liikeArvoJLabel;
    private javax.swing.JLabel liikeJLabel;
    private javax.swing.JLabel liikeNimiJLabel;
    private javax.swing.JLabel liikeTuottoJLabel;
    private javax.swing.JLabel liikkeenArvo;
    private javax.swing.JTextField liikkeenNimi;
    private javax.swing.JLabel liikkeenTuotto;
    private javax.swing.JLabel mokinArvo;
    private javax.swing.JTextField mokinNimi;
    private javax.swing.JLabel mokkiArvoJLabel;
    private javax.swing.JLabel mokkiJLabel;
    private javax.swing.JLabel mokkiNimiJLabel;
    private javax.swing.JButton myyLiike;
    private javax.swing.JLabel myyLiikeJLabel;
    private javax.swing.JButton myyMokki;
    private javax.swing.JLabel myyMokkiJLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton ostaLiike;
    private javax.swing.JButton ostaMokki;
    private javax.swing.JComboBox pelaajanLiikkeet;
    private javax.swing.JComboBox pelaajanMokit;
    private javax.swing.JLabel pelaajanNimi;
    private javax.swing.JLabel pelaajanRahat;
    // End of variables declaration//GEN-END:variables
    private OstoJaMyynti ostoJaMyynti;
    private OstoJaMyyntiActionListener actionlistener;
}
