package presidenttipeli.gui;

import javax.swing.JFrame;
import presidenttipeli.logiikka.Pankinjohtaja;
import presidenttipeli.logiikka.Peli;
import presidenttipeli.logiikka.Velkalaskuri;

/**
 * GUI jonka avulla pelaaja pystyy ottamaan velkaa tai maksamaan sitä pois.
 */
public class VelanhallintaGUI extends javax.swing.JFrame implements Runnable {

    public VelanhallintaGUI(Peli peli, JFrame frame, boolean pakkoOttaaVelkaa) {
        this.peli = peli;
        this.pakkoOttaaVelkaa = pakkoOttaaVelkaa;
        pankinjohtaja = peli.getPankinjohtaja();
        laskuri = new Velkalaskuri(peli.getNykyinenPelaaja());
        this.frame = frame;
    }

    @Override
    public void run() {
        initComponents();
        lisaaNappuloilleActionListener();
    }

    private void lisaaNappuloilleActionListener() {
        VelanhallintaActionListener listener = new VelanhallintaActionListener(
                hyvaksyTakaisinmaksu, hyvaksyVelanotto, maksurahaMinus100, maksurahaMinus1000,
                maksurahaPlus100, maksurahaPlus1000, ottorahaMinus100, ottorahaMinus1000,
                ottorahaPlus100, ottorahaPlus1000, suljeButton, maksurahat, ottorahat,
                pelaajanRahat, pelaajanVelat, this, rootPane, peli, laskuri, pankinjohtaja);
        hyvaksyTakaisinmaksu.addActionListener(listener);
        hyvaksyVelanotto.addActionListener(listener);
        maksurahaMinus100.addActionListener(listener);
        maksurahaMinus1000.addActionListener(listener);
        maksurahaPlus100.addActionListener(listener);
        maksurahaPlus1000.addActionListener(listener);
        ottorahaMinus100.addActionListener(listener);
        ottorahaMinus1000.addActionListener(listener);
        ottorahaPlus100.addActionListener(listener);
        ottorahaPlus1000.addActionListener(listener);
        suljeButton.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pelaajanRahat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pelaajanVelat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ottorahaMinus1000 = new javax.swing.JButton();
        ottorahaMinus100 = new javax.swing.JButton();
        ottorahat = new javax.swing.JTextField();
        ottorahaPlus1000 = new javax.swing.JButton();
        hyvaksyVelanotto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        maksurahaMinus1000 = new javax.swing.JButton();
        maksurahaMinus100 = new javax.swing.JButton();
        maksurahat = new javax.swing.JTextField();
        maksurahaPlus100 = new javax.swing.JButton();
        maksurahaPlus1000 = new javax.swing.JButton();
        hyvaksyTakaisinmaksu = new javax.swing.JButton();
        suljeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pelaajanNimi = new javax.swing.JLabel();
        ottorahaPlus100 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                sulje(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Pelaajan rahat:");

        pelaajanRahat.setText(laskuri.getPelaajanRahat() + " mk");

        jLabel2.setText("Pelaajan velat:");

        pelaajanVelat.setText(laskuri.getPelaajanVelat() + " mk");

        jLabel3.setText("Ota velkaa:");

        ottorahaMinus1000.setText("-1000");
        ottorahaMinus1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottorahaMinus1000ActionPerformed(evt);
            }
        });

        ottorahaMinus100.setText("-100");
        ottorahaMinus100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottorahaMinus100ActionPerformed(evt);
            }
        });

        ottorahat.setEditable(false);
        ottorahat.setText("00000");

        ottorahaPlus1000.setText("+1000");
        ottorahaPlus1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottorahaPlus1000ActionPerformed(evt);
            }
        });

        hyvaksyVelanotto.setText("OK");
        hyvaksyVelanotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyvaksyVelanottoActionPerformed(evt);
            }
        });

        jLabel4.setText("Maksa velkoja:");

        maksurahaMinus1000.setText("-1000");
        maksurahaMinus1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maksurahaMinus1000ActionPerformed(evt);
            }
        });

        maksurahaMinus100.setText("-100");
        maksurahaMinus100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maksurahaMinus100ActionPerformed(evt);
            }
        });

        maksurahat.setEditable(false);
        maksurahat.setText("00000");
        maksurahat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maksurahatActionPerformed(evt);
            }
        });

        maksurahaPlus100.setText("+100");
        maksurahaPlus100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maksurahaPlus100ActionPerformed(evt);
            }
        });

        maksurahaPlus1000.setText("+1000");
        maksurahaPlus1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maksurahaPlus1000ActionPerformed(evt);
            }
        });

        hyvaksyTakaisinmaksu.setText("OK");
        hyvaksyTakaisinmaksu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyvaksyTakaisinmaksuActionPerformed(evt);
            }
        });

        suljeButton.setText("Sulje");
        suljeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suljeButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Pelaaja:");

        pelaajanNimi.setText(peli.getNykyinenPelaaja().getNimi());

        ottorahaPlus100.setText("+100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(suljeButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pelaajanNimi))
                            .addComponent(ottorahat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(maksurahat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maksurahaMinus1000)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maksurahaMinus100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maksurahaPlus100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maksurahaPlus1000)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hyvaksyTakaisinmaksu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pelaajanRahat)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pelaajanVelat))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ottorahaMinus1000, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ottorahaMinus100)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ottorahaPlus100)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ottorahaPlus1000)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hyvaksyVelanotto)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pelaajanRahat)
                    .addComponent(jLabel2)
                    .addComponent(pelaajanVelat)
                    .addComponent(jLabel5)
                    .addComponent(pelaajanNimi))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ottorahaMinus1000)
                    .addComponent(ottorahaMinus100)
                    .addComponent(ottorahaPlus1000)
                    .addComponent(ottorahat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hyvaksyVelanotto)
                    .addComponent(ottorahaPlus100))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maksurahat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maksurahaMinus1000)
                    .addComponent(maksurahaMinus100)
                    .addComponent(maksurahaPlus100)
                    .addComponent(hyvaksyTakaisinmaksu)
                    .addComponent(maksurahaPlus1000))
                .addGap(18, 18, 18)
                .addComponent(suljeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ottorahaMinus1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottorahaMinus1000ActionPerformed

    }//GEN-LAST:event_ottorahaMinus1000ActionPerformed

    private void ottorahaMinus100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottorahaMinus100ActionPerformed

    }//GEN-LAST:event_ottorahaMinus100ActionPerformed

    private void ottorahaPlus1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottorahaPlus1000ActionPerformed

    }//GEN-LAST:event_ottorahaPlus1000ActionPerformed

    private void maksurahaMinus1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maksurahaMinus1000ActionPerformed

    }//GEN-LAST:event_maksurahaMinus1000ActionPerformed

    private void maksurahaMinus100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maksurahaMinus100ActionPerformed

    }//GEN-LAST:event_maksurahaMinus100ActionPerformed

    private void maksurahaPlus100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maksurahaPlus100ActionPerformed

    }//GEN-LAST:event_maksurahaPlus100ActionPerformed

    private void maksurahaPlus1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maksurahaPlus1000ActionPerformed

    }//GEN-LAST:event_maksurahaPlus1000ActionPerformed

    private void hyvaksyVelanottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyvaksyVelanottoActionPerformed

    }//GEN-LAST:event_hyvaksyVelanottoActionPerformed

    private void maksurahatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maksurahatActionPerformed

    }//GEN-LAST:event_maksurahatActionPerformed

    private void suljeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suljeButtonActionPerformed

    }//GEN-LAST:event_suljeButtonActionPerformed

    private void hyvaksyTakaisinmaksuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyvaksyTakaisinmaksuActionPerformed

    }//GEN-LAST:event_hyvaksyTakaisinmaksuActionPerformed

    private void sulje(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_sulje
        frame.setVisible(true);
        frame.setEnabled(true);
        if (pakkoOttaaVelkaa) {
            peli.yritaSuorittaaTapahtumaaToisenKerran();
        }
    }//GEN-LAST:event_sulje

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hyvaksyTakaisinmaksu;
    private javax.swing.JButton hyvaksyVelanotto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maksurahaMinus100;
    private javax.swing.JButton maksurahaMinus1000;
    private javax.swing.JButton maksurahaPlus100;
    private javax.swing.JButton maksurahaPlus1000;
    private javax.swing.JTextField maksurahat;
    private javax.swing.JButton ottorahaMinus100;
    private javax.swing.JButton ottorahaMinus1000;
    private javax.swing.JButton ottorahaPlus100;
    private javax.swing.JButton ottorahaPlus1000;
    private javax.swing.JTextField ottorahat;
    private javax.swing.JLabel pelaajanNimi;
    private javax.swing.JLabel pelaajanRahat;
    private javax.swing.JLabel pelaajanVelat;
    private javax.swing.JButton suljeButton;
    // End of variables declaration//GEN-END:variables
    private Peli peli;
    private Velkalaskuri laskuri;
    private Pankinjohtaja pankinjohtaja;
    private JFrame frame;
    private boolean pakkoOttaaVelkaa;
}
